cmd/dosa/main.go
cmd/dosa/options.go
cmd/dosa/schema.go
cmd/dosa/schema_test.go
cmd/dosa/scope.go
cmd/dosa/scope_test.go
connectors/devnull/devnull.go

Previously, users had to provide `--service` flag for any non-production scope.
This also adds configuration for positional arguments to be required for `scope` subcommands and to be optional for `schema` subcommands.
Example output:
```
$ dosa scope create
Error: the required argument `scopes (at least 1 argument)` was not provided
```
```
$ dosa scope create -h
Error: Usage:
dosa [OPTIONS] scope create scopes...
...
```
```
$ dosa schema check -h
Error: Usage:
dosa [OPTIONS] schema [schema-OPTIONS] check [check-OPTIONS] [paths...]
...
```

[CLI] Set service name dynamically if not provided

---

connectors/yarpc/helpers.go
connectors/yarpc/helpers_test.go
connectors/yarpc/yarpc.go
connectors/yarpc/yarpc_test.go

This error seems to come up a lot, especially when a UUID is not
supplied. This change should result in a better error message for
these cases.

Handle conversion errors for bad UUIDs

---

examples/testing/README.md
examples/testing/testing.go
examples/testing/testing_test.go
range.go
range_test.go
scan.go
scan_test.go

I was going to write some unit tests for some code that was using DOSA, and I realized I didn't have a good way to tell the mock DOSA client that it should expect a Range call with a certain RangeOp. So I went ahead and made a gomock Matcher for the RangeOp (and the ScanOp as well). The one thing I couldn't really figure out how to do was to compare on the DomainObject of the ScanOp when matching ScanOps. I figure it's not too big of a deal, but if anyone knows how I would love to be enlightened.

Add Matchers for RangeOp and ScanOp

---

client.go
client_test.go
connector.go
connectors/base/base.go
connectors/base/base_test.go
connectors/devnull/devnull.go
connectors/devnull/devnull_test.go
connectors/memory/memory.go
connectors/memory/memory_test.go
connectors/random/random.go
connectors/random/random_test.go
connectors/yarpc/helpers.go
connectors/yarpc/yarpc.go
connectors/yarpc/yarpc_test.go
examples/testing/doc.go
registry.go
registry_test.go

Will not be merged until the TODO list size is smaller (perhaps 0)
Implemented: CreateIfNotExists, Read, Upsert, Delete
Partially implemented: Range, Scan
TODO:
Range and Scan always return the whole partition that matches.
As a result, they don't return or parse continuation tokens

Add memory connector

---

connectors/base/base_test.go
connectors/devnull/devnull.go
connectors/devnull/devnull_test.go
connectors/random/random.go
connectors/random/random_test.go

Standard behavior for the cassandra connector is to not return an error when an attempt is made to remove an entity that doesn't exist. Yet, the devnull and random connectors do just this. I would argue the cassandra connector does the "correct" thing, and we should have the devnull and random connectors follow suit. If you try to delete something and that thing doesn't exist, then it has effectively been deleted. Mission accomplished.
I'm pretty confident about this behavior for devnull, but less so on the random one. Random, in my head, represents an essentially immutable datastore if I'm understanding it correctly. You can only get things from it, not change what's in it. If that's the case, then I would argue the correct behavior is for all modification methods to fail with some …

don't return errors for remove

---

client.go
config/config.go
config/config_test.go
registry.go
registry/registry.go
registry/registry_test.go
registry_test.go

This adds a new `registry` package which implements support for "auto-discovery" of DOSA entities. It was broken out of #151. This will be used in subsequent changes to add support for UberFx.

Add support for entity discovery

---

glide.lock
glide.yaml

Just a run of `glide up`. I need the newest version of our generated thrift code so I can use it in our yarpc connector.
This change was originally included in #166 but I'm pulling it out into it's own PR. I'm doing this because @rkuris pointed out that our yarpc dependency also got updated and was concerned about our pinning of it. A look at our `glide.yaml` file reveals we have yarpc pinned to `^1.7.1`. @rkuris does that sound right to you? Or should we pin it to a more fixed version?

[Hard] Update glide dependencies

---

registry.go
registry/registry.go
registry/registry_test.go

This fixes a bug where the new registry package used for auto-discovery wasn't dereferencing correctly. Along the way, I noticed that we were using `fmt.Errorf` in a couple places so I went ahead and replaced them with `errors.Errorf`. And I added missing test coverage.

Fix registry and add missing coverage

---

client.go

Looks like there was some copy pasta when wrapping errors for the `ScanEverything` function. Let's fix these wraps and save some developer sanity.

[easy] fix error message wraping

---

connectors/yarpc/yarpc.go
connectors/yarpc/yarpc_test.go

This is part of a broader effort to enable the removal of a range of values.  The Yarpc connector is the last connector that does not have a RemoveRange reciever function on it. Once the yarpc connector has this function, we can actually alter the Connector interface to include a RemoveRange function and then add the functionality to the client.

add RemoveRange to yarpc connector

---

connector.go
connectors/base/base.go
connectors/base/base_test.go
mocks/connector.go

We've now got remove range in all of our connectors*, so let's add it to the connector interface.
*actually, we're still missing it in the base connector, but we'll add that here too.

add RemoveRange to Connector interface

---

client/client.go
client/client_test.go
registry/registry.go
registry/registry_test.go

This corrects an oversight in the design of the `dosaclient` interface which was the assumption that entities could be "auto-discovered" -- this is not feasible for environments where only a binary is distributed and thus there is nothing to be "discovered". This maintains backwards compatibility by allowing the associated client and registry constructors to optionally take a slice of entities that will cause entity discovery to be subverted.

Allow entities to be provided explicitly to dosaclient.New

---

connectors/memory/memory.go
connectors/memory/memory_test.go

Previously, we got dosa.ErrNotFound errors. This
is inconsistent with the cassandra connector.

Memory connector should return empty sets

---

cmd/dosa/main.go
cmd/dosa/options.go
cmd/dosa/options_test.go
cmd/dosa/schema.go
cmd/dosa/schema_test.go
cmd/dosa/scope_test.go

RE: [DOSA-1011](https://jira.uberinternal.com/browse/DOSA-1011) - If `$USER` contains invalid characters and subsequently, a caller name result in `dosacli-$USER`, invoking YARPC dispatcher causes a panic. 
To reproduce:
```
USER=evan.culver.test dosa scope create eculver_test # panics
```
To fix the issue, I create two new flag types, one for caller and the other for scope. Each of these flags do the "sanitizing" of incoming values for their respective flag. For caller, '.' is replaced by hyphen (since underscores are not allowed) and for scope, '.' is replaced by underscores.
For example, the example above would create the scope "eculver_test" by calling the dosa-dev-gateway as "dosacli-evan-culver-test".
Similarly for schema operations, this:
```
USER=evan.culver.test dosa schema …
```

Validate caller name before invoking YARPC dispatcher

---

range.go

Fixes [DOSA-1049](https://jira.uberinternal.com/browse/DOSA-1049) - Docstring for RangeOp.Limit misrepresents default behavior.

[easy] Update RangeOp.Limit docstring

---

.gitignore
cmd/dosa/schema_test.go
connectors/yarpc/helpers.go
doc.go
entity.go
entity_parser.go
entity_parser_test.go
entity_test.go
finder.go
finder_test.go
registry/registry_test.go
scan_test.go
schema/avro/avro.go
testentity/named_import_testentity.go
testentity/testentity.go
type.go
type_test.go

This change adds basic 4 nullable types to entity parser (JIRA-926/929). It includes a few bug fixes to existing code as well. This change also covers parts of the request path. Response path along with remaining Yarpc Connector changes will be covered in following CRs.

Add nulltypes to parser

---

glide.lock
glide.yaml

Our glide.yaml file needed some love. I've implemented the following changes:
- the go_flags package now tracks a semantic version
- several packages have been moved to testImport since they're not actually needed to compile any of our real code
- our yarpc dependencies have been cleaned up as well. We actually specify which subpackages we need, change the semver to ^1.7.1 and get rid of the reference to github.com/uber-go/yarpc which isn't actually used anywhere in our code.

glide cleanup

---

connectors/memory/memory.go
connectors/memory/memory_test.go

This implements continuation tokens for the Range() operator in the
memory connector.  Just before returning from Range(), if the length
of the return value is longer than requested, we encode the data
in the last value returned to the user.  The encoding is a base64
encoded gob.
When a token is supplied on a future call to Range(), we still find
all the rows, and then decode the token, and look for that value
in the result set.  If we find it, then we just start at the next
value. If it's not there, that's okay too; we just start at the
next value in the set. The latter can only happen when the specific
value in the token has been deleted.

Add support for memory connector Range() tokens

---

entity_parser_index_test.go
finder.go

Bug:
dosa cli can't detect embedded index field
```
type MultipleIndexes struct {
Entity       `dosa:"primaryKey=PrimaryKey"`
Index        `dosa:"key=Data, name=SearchByData"`
SearchByDate Index `dosa:"key=Date"`
PrimaryKey   int64
Data         string
Date         time.Time
}
```

Fix the bug that finder can't find embedded dosa.Index field

---

connectors/memory/memory_test.go
registry.go
registry_test.go

`NewRegisteredEntity` has a bug where the entity that get's registered doesn't properly copy over the secondary Indexes for a given `EntityDefintion`, it only sets the name, key, and columns.
This causes Range lookups on secondary indexes to fail for the in-memory connector.
Let's fix this problem by just using the full `EntityDefinition` that's available to us via the `table` that's passed in. This way, if we ever add any more fields to the `EntityDefinition` in the future, they'll be automatically included in the `RegisteredEntity`.

Ensure Registered Entities are created with Index information

---

client.go
client_test.go
conditioner.go
conditioner_test.go
mocks/client.go
pager.go
range.go
range_test.go
remove_range.go
remove_range_test.go
scan.go

Couple things
1. The `RangeOp` has a `ScanOp` inside it. This is kinda weird. I can see why it was done, since they share so many similarities, however, I don't think this is the best way to organize the code. Let's extract their common aspects out into a struct called a `pager`. Now, both a `ScanOp` and a `RangeOp` have a pager embedded in them. This makes more sense.
2. Now that we've got `RangeOp` and `ScanOp` untangled, let's actually not use `RangeOp` for the `RemoveRange` api anymore. Using the `RangeOp` for `RemoveRange` is misleading because `RemoveRange` completely ignores the `token`, `limit`, and `fieldsToRead` aspects of `RangeOp`. Instead, let's extract their common components into a shared, embedded struct called a `conditioner`, and create a new `RemoveRangeOp` struct …

Better RemoveRange API

---

script/build_cli.sh

This makes it easier to build tarballs for releases. It's relatively simple (and dumb) in when run from project root, will spit out tarballs into `./out`:
```
./script/build_cli.sh v0.0.0
DONE
Darwin package built: ./out/dosa-darwin-v0.0.0.tar.gz
Linux package built: ./out/dosa-darwin-v0.0.0.tar.gz
```

[tools] add utility script for building release packages

---

connectors/yarpc/yarpc.go

Early returns are generally easier to read. Let's switch to using early returns here instead of some deeply nested if statements. Also, we can now say exactly which field is missing, giving a more specific error message.

[easy] switch to early return

---

Makefile
client.go
client_test.go
mocks/client.go

Customers often want to fetch an entire range of values. Doing so with the current `Range` function provided by the `Client` is tedious. It requires writing the same boiler plate code over, and over again. Let's provide a convenience function so that customers don't have to write their own.

Provide convenience function for fetching entire range

---

connectors/yarpc/yarpc.go
connectors/yarpc/yarpc_test.go

RE: [DOSA-1010](https://jira.uberinternal.com/browse/DOSA-1010).
This adds two new error types to the `connectors/yarpc` package and wraps existing admin client methods to deliver more discernible error messages to user.
Examples from using the cli...
Invalid service name:
```
dosa schema upsert --prefix infra.evan_culver --service foobar ./testentity
Status: NOT OK
Error: UpsertSchema failed, directories: [./testentity], excludes: [_test.go], scope: eculver: YARPC UpsertSchema failed: the gateway "foo" refused to handle scope "eculver"; probably because of a mismatch between gateway and scope in your configuration or initialization
```
Connection refused:
```
dosa schema upsert --prefix infra.evan_culver --service foobar ./testentity
Status: NOT OK
Error: UpsertSchema failed, …
```

Improve yarpc connector errors

---

glide.lock
glide.yaml

We removed some types from our IDL so builds are failing for upstream dependencies when testing against master.

Update dependencies to pull in latest dosa-idl

---

config/config.go
config/config_test.go

After we removed the `dosaclient` package in #211, we were left with only one option for client creation which is a lot of boilerplate. To make configuration simpler, this enhances the existing `config.NewClient` method to understand arbitrary connector args.

Make config.NewClient smarter

---

CHANGELOG.md
version.go

I have created a changelog for easier release notation and have bumped the version to 2.3.0. Please review the notes in CHANGELOG.md to make sure I haven't missed anything.

Prepare v2.3.0

---

testclient/testclient.go
testclient/testclient_test.go

This creates a simple DOSA client useful for testing that can't be done with simple mocks. This client utilizes the in-memory connector as it's backing store.

add testclient to DOSA

---

connectors/memory/memory.go
connectors/memory/memory_test.go

This diff registers time.Time in the `makeToken` and `decodeToken` functions, allowing the `Scan` and other functions to support `time.Time`.
Fixes T1305491

Support time.Time in the in-memory connector

---

connectors/yarpc/yarpc_test.go

Some how the tests for scan got out of order. If you look at the ordering of the mock responses for scan on lines 816 and 819 you'll see what we really should be doing is testing the generic error case first and then the not found error case.

Fix yarpc tests

---

cmd/dosa/main.go
cmd/dosa/options.go
cmd/dosa/schema.go
cmd/dosa/schema_test.go
cmd/dosa/scope.go

This removes all references to `dosa-dev-gateway` from the CLI and updates the defaults to use `dosa-gateway`. Users can still provide a service override if they choose to use `dosa-dev-gateway` but this is just another step in completely deprecating all notions of being _dev_ (vs prod) specific.

Remove dev-gateway

---

.build/deps.mk
glide.lock
glide.yaml

Let's run a `glide up` to get new versions of our dependencies. Specifically, I'd like to pick of the new version of `github.com/uber/dosa-idl`. It includes automatic tchannel sanitization added by https://github.com/uber/dosa-idl/pull/21
There were also some issues with the two mvdan programs specified in our `glide.yaml` file. I couldn't find where we ever actually use these two things, so I removed them from our `glide.yaml`

Update our glide dependencies

---

connectors/memory/memory.go
connectors/memory/memory_test.go
range.go

It's illegal to remove multiple items based on an index. This change
enforces that, by not looking at indexes when calling RemoveRange.

Fix RemoveRange panic with index criteria

---

entity_parser.go
entity_parser_index_test.go
entity_parser_key_parser_test.go
finder.go
finder_test.go

When upserting the schema, an unexported index filed will be silently ignored. Adding this validation to error loud to the client.

Ensure index name is exported in the entity during schema validation 

---

cmd/dosa/main_test.go
cmd/dosa/schema.go
cmd/dosa/schema_test.go
connectors/memory/memory_test.go
metrics/noops_test.go

Make scope name required for CLI schema command, i.e. check, upsert, and status.
Currently it defaults to the username which can easily cause confusions and mistakes. By make CLI users to explicitly specify scope name, it's less error-prone:
-  it prevents users from accidentally accessing/modifying schema on unintended scopes
-  it avoids ambiguous error messages due to using the wrong scope name.

Make scope name required in CLI schema commands

---

names.go

`invitertoinviteepromotioninstance has length 32, max allowed is 33` The error message makes the max allowed number at wrong place.

fix the error message

---

connectors/cache/fallback.go
connectors/cache/fallback_test.go

The fallback connector had a bug where it was not returning values as pointers. yarpc does this, so if the fallback is supposed to be a drop in replacement, it needs to have the same behavior

Change fallback connector to use only gob encoding

---

connectors/base/base.go
connectors/routing/connector.go
entity.go

This is needed to route the `canUpsertSchema` request to the correct connector.

Overwrite canUpsertSchema in routing connector 

---

CHANGELOG.md
connectors/cache/fallback.go
connectors/cache/fallback_test.go

Previously we would upsert to both dosa and the cache in parallel in goroutines. However, this has the weird behavior where the dosa path might fail but the cache call succeeds so the data will be found in cache but not in dosa. We should not have this inconsistent behavior and wait to see if the dosa call succeeds.

Upsert to fallback only on successes

---

client.go
connectors/cache/fallback_test.go
connectors/memory/memory.go
mocks/client.go

Users want to have someway to tell whether a object is registered as DOSA object. Registrar has `find` method so that users can tell if an domainObject is registered or not.

expose the IsDomainObject API

---

script/build_cli.sh

There's a small typo in the script for generating the cli. Let's fix it.

fix output message in build_cli script

---

connectors/memory/memory.go
connectors/memory/memory_test.go

When trying to remove an object with an index that contains a superset of the primary key fields, the in-memory connector crashes. This fixes the issue.

fix the remove api bug in memory connector

---

connectors/memory/memory.go
connectors/memory/memory_test.go

Compound Partition Keys are completely broken with the in-memory connector. Each time a value of a partition key is encoded in `partitionKeyBuilder` the previous encoded partition key value is completely overwritten. This means for entities that have more than one column as part of their partition key, only the last partition key value is used when creating the encoded partition key value.
The result of this is that if two rows have the same value for the last column that's part of their partition key (but different values for the other columns making up their partition key), the second row will completely overwrite the first (since the resulting encoded partition key is the same for both rows).
Let's fix this by concating all of the encoded values for each partition key column and using …

Fix Compound Partition Keys in In-Memory Connector

---

connectors/memory/memory.go
connectors/memory/memory_test.go

Currently, when reading, ranging, or scanning from the in-memory connector, the connector returns references to internal data (in the forms of slices and maps). This allows callers to read/write internal data without acquiring the appropriate locks inside the in-memory connector, resulting in race conditions.
By returning copies of the values stored within the in-memory connector, we can ensure the values returned to the caller have no references to the internal state within the in-memory connector and prevent data races.

fix bad race conditions in memory connector

---

connectors/memory/memory.go
connectors/memory/memory_test.go

When upserting (and similarly with CreateIfNotExists) the map that is placed into the in-memory connector is the same reference that the caller also owns. This means that the caller can then make future mutations to that map (which is now considered part of the internal state of the in-memory connector), without acquiring the necessary locks. This causes a race condition.
We can fix this by copying data that is being upserted so the in-memory connector fully owns the data that is part of it's internal state.

fix upsert race condition

---

CHANGELOG.md
connectors/cache/fallback.go
connectors/cache/fallback_test.go

Turns out you can do partial updates where you write only some columns. 
Currently we are writing to redis on upsert, which means partial data is getting written to the cache. Invalidate the cache instead of writing partial results.

Invalidate fallback cache on upsert to dosa

---

connectors/yarpc/yarpc.go
connectors/yarpc/yarpc_test.go

The yarpc connector does not properly unpack 404s for each error on an entity. Let's add the code so that if the entity isn't found, we properly create a NotFound error so.

properly interpret not found errors in MultiRead

---

CHANGELOG.md
version.go

This PR does all of the necessary steps for preparing a release of dosa version 2.5.3. Namely, it updates the version number in `version.go` and brings the `CHANGELOG.md` file up to date.

Prepare 2.5.3 release

---

CHANGELOG.md
connectors/cache/fallback.go
connectors/cache/fallback_test.go

Safer to just remove from the cache, regardless of if the dosa call actually succeeded

Always remove from cache on dosa upsert

---

connectors/memory/memory.go
connectors/memory/memory_test.go

This implements the missing multi upsert and multi remove methods in the memory connector. As noted, this does not use a lock when removing and upserting the set of entities. There is no such guarantee provided in the interface and thus we do not do it here.

Implement multi upsert and multi remove methods in memory connector

---

.travis.yml
connectors/cassandra/datastore_crud_test.go
connectors/cassandra/datastore_query_test.go
connectors/memory/memory_test.go
connectors/random/random.go
glide.lock
glide.yaml
type.go
type_test.go

Also cleanup: replace all calls to `uuid.NewV4().String()` with `dosa.NewUUID()` to keep the call to the breaking function in one place.

Satori uuid 1.2

---

registrar.go
registrar_test.go

The `fqnIndex` is never used in the `prefixedRegistrar`. It's dead code. Let's remove it.

remove fqnIndex

---

names.go
names_test.go
registrar.go
schema/avro/avro.go
schema/avro/avro_test.go

FQNs are a hold over from DOSA V1. We don't really use them anymore. Let's clean up some code here in the client and remove the notion of them. Let's also add a few more tests to ensure that we're only ever accepting valid name prefixes.

remove notions of FQNs

---

CHANGELOG.md
connector.go
connectors/base/base.go
connectors/devnull/devnull.go
connectors/random/random.go
connectors/routing/connector.go
connectors/yarpc/yarpc.go
mocks/connector.go

We've run into a usecase where it would be useful to query a connector for the schema of a given entity. Let's add a function to the Connector interface that allows us to do that.

add GetEntitySchema to connector interface

---

CHANGELOG.md
connectors/routing/connector.go
connectors/routing/connector_test.go

The `PluginFunc` is never used on the routing connector. Let's get rid of it since its extra code for us to support.

remove unused code from routing

---

CHANGELOG.md
connector.go
connectors/base/base.go
connectors/devnull/devnull.go
connectors/random/random.go
connectors/routing/connector.go
connectors/yarpc/yarpc.go
mocks/client.go
mocks/connector.go

I goofed up and used `EntityInfo` when I should have use `EntityDefinition` for the new `GetEntitySchema` function on the `Connector` interface. Let's correct that.

Change to EntityInfo to EntityDefinition

---

connectors/redis/redis.go
connectors/redis/redis_test.go

Background: 
Redis connector is currently used in Fallback cache for eats. Recently we are going to build capacity cache using Redis. In order to avoid key collision with these two kinds of cache, I am introducing a new field - keyPrefix to Redis Connector.
The change is to append prefix only if it's set with config. It won't change any current key that is being used in redis.

Add keyPrefix to the config of redis connector

---

connectors/memory/memory.go
connectors/memory/memory_test.go
glide.lock
glide.yaml
type.go

The satori/go.uuid package has some serious known problems, particularly
with the generation of V4 UUIDs. It's also no longer maintained. The
recommended replacement is gofrs/uuid.
Additionally, the gofrs team accepted the change I made to the uuid
package about two years ago and released 3.1.0 which includes a feature
needed by the DOSA memory connector. This also removes that workaround.

Switch to gofrs/uuid

---

CHANGELOG.md
entity.go
entity_parser.go
entity_parser_index_test.go
entity_parser_key_parser_test.go
entity_test.go
finder.go
finder_test.go

The index table is built on selecting all the fields in the entity. It’s costly to read/write with large payload. Using columns tag to make it flexible,  which could reduce the payload when build the materialized view.
This pull is to extend the annotation. Users could choose to use **columns=(field1, field2, field3)** to limit the columns required to build the index table.

Add a 'columns' tag for Index definitions that defines which fields should be denormalized into the index

---

entity.go
entity_test.go

1. fields in columns tag must refer to a column.
2. a column cannot be used twice.

cover corner cases checking columns tag valid usage

---

entity.go
entity_test.go

Why I am doing this change?
Here is the error messages in integration test after using this dosa version.
```
Err: \"incompatible schema: index \\\"searchbystr\\\" mismatch: (&{(strv, an_uuid_key ASC, strkey ASC, int64key ASC) []} vs &{(strv, an_uuid_key ASC, strkey ASC, int64key ASC) []})\",",
```
After print the struct variables to explore more.
```
index searchbystr mismatch: (Key: &{(strv, an_uuid_key ASC, strkey ASC, int64key ASC), Columns: []string{}} vs &{ Key: (strv, an_uuid_key ASC, strkey ASC, int64key ASC) , Columns: []string(nil)}
```
They are not deep equal.
After I debug throughout the whole lifecycle how the values change from DOSA cli to gateway to Schema service. I found out the value `Columns: nil` changed into `Columns: []string{}` right here. …

index columns zero value is []string(nil) but not []string{}

---

CHANGELOG.md
cmd/dosa/main.go
cmd/dosa/main_test.go
cmd/dosa/schema.go
cmd/dosa/schema_test.go

Calling it `schema check` leads to confusion with the API method `CheckSchema`. If `CheckSchema` fails at service startup, people think they can debug the situation with `dosa schema check` -- which is not true.

Rename CLI command "schema check" to "schema upsertable"

---

entity.go
entity_test.go

```
var s = make([]int, 3)
n := copy(s, []int{0, 1, 2, 3}) // n == 3, s == []int{0, 1, 2}
```
`copy(dst, src []T) int`
The number of elements copied is the minimum of len(src) and len(dst).
https://golang.org/ref/spec#Appending_and_copying_slices
In our use case, copy is not the right way to clone.
**make test**
**go test -v --run TestClone**

use append but not copy to clone

---

cmd/dosa/client.go
cmd/dosa/query.go
cmd/dosa/range.go
cmd/dosa/read.go

There are some ignored errors in the CLI query code. Although those errors will never happen, we should handle them to achieve the best practices in GO.

handle the ignored error in CLI query codes

---

CHANGELOG.md
cmd/dosa/main.go
cmd/dosa/options.go
connectors/yarpc/yarpc.go
connectors/yarpc/yarpc_test.go
glide.lock
glide.yaml

This change allows us to configure the dosa client transport as part of the yarpc connector config. 
YARPC does the heavy lifting, allowing us to use any supported transport (`tchannel`, `http`, and `grpc` are currently supported). The existing client behavior always uses tchannel, which is quickly becoming deprecated. 
I added an option (`--transport`) to the cli to allow cli users to specify their transport. By default, we fallback to tchannel. I chose not to expose the grpc transport, as it is still experimental and I do not have a grpc server to test against yet- the transport built is valid according to the grpc yarpc documentation.

Parameterizing yarpc transport

---

CHANGELOG.md
connectors/routing/config.go
connectors/routing/config_test.go
connectors/routing/routing_config.go
connectors/routing/routing_config_test.go
entity.go
entity_test.go
version.go

Instead of `reflect.DeepEqual` use sensible comparisons.
Also made `newRule` package-private to remove a lint check.

Cleanup String methods, and do not use reflect.DeepEqual to compare entities

---

CHANGELOG.md
cmd/dosa/scope.go

On scope drop success, print a message reminding the user that they need to wait 10 minutes before re-creating the scope with the same name.

Update 'scope drop' success message

---

CHANGELOG.md
connectors/routing/connector.go
connectors/routing/resolver.go

Routing: public method to map (scope,prefix) to a cluster name

---

CHANGELOG.md
connectors/routing/resolver.go
entity.go
range.go
range_conditions.go

There is absolutely no reason to have _N_ versions of the identity transform function.

Allow the function pointer to be nil in EnsureValidRangeConditions

---

CHANGELOG.md
entity.go

Docstore does not implement index aliases yet.

Add the concept of a table alias for an index

---

CHANGELOG.md
cmd/dosa/schema.go
connectors/yarpc/yarpc.go
version.go

The CLI needs to be released, v3.4.2 is now pretty old....
Also removed unused argument in `wrapError()` in the yarpc connector.

Better CLI errors

---

entity_parser.go
names.go

`NormalizeName` is completely the wrong thing to use, an ETL tag is not necessarily a "name": `on` is a reserved word is not a legal name!
Also discovered that the list of reserved words is not really definitive: `uuid` and `type` are both on the "reserved" list but are fine as field names; but we know `token` is definitely not OK.

Fix bug in ETL parsing

---

names_test.go

Apparently I forgot this test when I cleaned up the reserved words list.

Fix failing test

---

glide.lock
glide.yaml

A somewhat-revert of b2a103e -- which changed things like `^2.6` into `v2.6` etc.

Attempt no. 2 for glide up

---

CHANGELOG.md
version.go

v3.4.16 sends column order with all schema definitions.

Update version to 3.4.16

---

CHANGELOG.md
connectors/yarpc/helpers.go
connectors/yarpc/helpers_test.go
version.go

Should have included this in the previous diff (facepalm)....

Make thrift decode of EntityDefinition respect column ordering.

---

entity_parser.go
entity_parser_key_parser_test.go
entity_parser_test.go

Variable names cannot be `foo0`, `foo1`, `foo2`, ...

More cleanup

---

connector.go
range_conditions.go

There are many gateway tests which depend on `Operator.String()` returning `Eq` etc., so put that back, and define `Symbol()` to return the symbolic operators.

Preserve Operator.String(), add Operator.Symbol()

---

CHANGELOG.md
connectors/cache/fallback.go
connectors/cache/fallback_test.go

1. We are using existing 'methodName' context already being set and used in EPG
2. Create initialization function to be called as contructor options
3. New configuration defaults to NO-OP if config is not set or empty else is enforced

Add cache configuration per endpoint in fallback cache

---

CHANGELOG.md
connectors/cache/fallback.go
connectors/cache/fallback_test.go

1. Since we now allow cache configuration per endpoint and per entity,
we split the cache checks to two checks
2. The reads checks both the endpoint and entity to decide to cache in
fallback
3. The writes checks only the entity to decide to invalidate the cache

Split isCacheable check for read and write

---

CHANGELOG.md
connectors/cache/fallback.go
connectors/yarpc/helpers.go
connectors/yarpc/helpers_test.go
entity.go
entity_parser.go
entity_parser_key_parser_test.go
entity_parser_test.go

A field in an entity may define the max size by using the `maxlen` tag. Example:
```
UserName string `dosa:"maxlen=100,name=db_user_name"`
```
However most of this diff is just sending the entity tags into the YARPC connection. (I don't know why the implementation was never completed.)

Allow a field's max-size to be specified in the entity

---

cmd/dosa/client.go

Currently the error messages are hard-coded and hide the actual error which makes debugging hard.

Return actual error message during client intialization
