client.go
client_test.go

This functionality won't be ready until 2.1.

Remove Multi* methods from client interface

---

client.go
client_test.go

Named everything.
Also added some notes about what you must fill out before
calling various methods

Additional documentation for Client interface

---

connectors/memory/memory_test.go
connectors/random/random_test.go
entity.go
entity_test.go
finder.go
names_test.go
range_conditions.go
schema/uql/uql.go

Corrects typos and unused variables, no functional
differences

Report card improvements

---

null_bool.go
null_bool_test.go
null_int64.go

Added a NullBool type. Plus a minor UT change to increase coverage for NullInt64 type.

Adding NullBool type.

---

connectors/devnull/devnull.go
connectors/devnull/devnull_test.go
connectors/random/random.go
connectors/random/random_test.go

As we continue to add support for the RemoveRange operation, implementation for it need to be added to the devnull and random connectors.

add RemoveRange to devnull and random connectors

---

errors.go
null_int64.go
null_int64_test.go

Add license header to new files

---

connectors/memory/memory.go
connectors/memory/memory_test.go

We'd like to add the ability to remove a range of values from DOSA. This adds that ability to the in-memory connector.

add RemoveRange for in-memory connector

---

null_bool.go
null_bool_test.go

Not sure why these weren't added by the pre-commit hook.

Adding license headers.

---

NullString.go
null_float64.go
null_float64_test.go
null_string_test.go

NullTime and NullUUID to follow.

NullString and NullFloat64

---

connectors/memory/memory.go
connectors/memory/memory_test.go

Also adds a test for this edge case

Fix bug when only one value is in the range

---

connectors/yarpc/helpers.go
connectors/yarpc/helpers_test.go
entity.go
entity_parser.go
entity_parser_index_test.go
entity_test.go
finder.go
glide.lock

Add index thrift converter 
Change indexes from array to map (it makes test easy)

index type converter

---

client.go
client_test.go
mocks/client.go

This adds the ability for the dosa client to call remove range

add remove range to client

---

client.go
client_test.go
connector.go
connectors/yarpc/helpers.go
connectors/yarpc/helpers_test.go
doc.go
entity.go
entity_parser.go
entity_parser_index_test.go
entity_parser_key_parser_test.go
entity_test.go
finder.go
finder_test.go
glide.lock
range_conditions.go
range_conditions_test.go

All the code change for the index features here.

Index feature

---

connectors/memory/memory.go
connectors/memory/memory_test.go
entity.go
entity_test.go
range.go

Adds support for secondary indexes in memory; see individual commits for changes

Memory connector secondary index support

---

schema/cql/cql.go
schema/cql/cql_test.go

Adds template information for secondary indexes

Add support for secondary indexes in dump output

---

connectors/routingconnector/config.go
connectors/routingconnector/config_test.go
connectors/routingconnector/connector_config.go
connectors/routingconnector/connector_config_test.go
connectors/routingconnector/routing_config.go
connectors/routingconnector/routing_config_test.go
connectors/routingconnector/routing_connector.go
connectors/routingconnector/routing_connector_test.go
glide.lock
glide.yaml

- create configuration struct and interfaces
- create basic routing connector interface without implementing methods
- error handlings are not fully done

Add RoutingConnector interface

---

cmd/dosa/schema_test.go
connectors/redis/redigo.go
connectors/redis/redigo_test.go
connectors/redis/redis.go
connectors/redis/redis_test.go
connectors/redis/util.go
connectors/routing/connector.go
finder_test.go
glide.lock
glide.yaml
testentity/keyvalue.go

v0 of redis connector implementation

Redis connector

---

connectors/yarpc/yarpc.go

It is misleading to customers to mention YARPC in error messages when it doesn't have anything to do w/ YARPC itself. This should quell some of the noise that the RPC team is receiving on our behalf.

Un-mention YARPC

---

connectors/redis/redigo.go
connectors/routing/config.go

There are a few formatting issues in some of our connectors that need to be fixed. I re-ran gofmt on them.

fix connector formatting issues

---

CHANGELOG.md

Updates the change log for the 2.4.0 release

cut 2.4.0 release

---

connectors/memory/memory.go
connectors/memory/memory_test.go
connectors/routing/connector_test.go

The existing findInsertionPoint method doesn't return the right insertion point due to the comparison  returns the incorrect value which results the pagination in the range doesn't work correctly.

Fix the memory connector findInsertionPoint bug

---

CHANGELOG.md
version.go

We want to do a new release of the client. Let's update the changelog and the version.

update version to report the proper version number

---

connectors/cache/fallback.go
connectors/cache/fallback_test.go

There are a few fmt issues with the fallback connector. Small fix.

fix some formatting errors in fallback connector

---

version.go

Switch version back to dev for now.

switch version back to dev

---

CHANGELOG.md
connectors/cache/fallback.go
connectors/cache/fallback_test.go

Actual code changes are very minimal, but I did semi-heavily refactor the tests in order to make them easier to read and with better naming, so it unfortunately looks like a lot of changes

Fallback connector MultiUpsert and MultiRemove implementations

---

CHANGELOG.md
connectors/cache/fallback.go
connectors/cache/fallback_test.go

DRY up writing to fallback

---

entity.go
entity_test.go

Fix comments in IsCompatible: change name and rename parameters

---

client.go
cmd/dosa/main.go
entity.go
entity_parser.go
entity_parser_test.go
finder.go
mocks/connector.go
names.go
names_test.go

They're used by the scope code in the gateway

IsValidName and NormalizeName need to be exported

---

README.md
client.go
cmd/dosa/main_test.go
cmd/dosa/schema.go
cmd/dosa/schema_test.go
doc.go

Let's not remove the old name of the option that people may already be used to.....
And some docs fixes

CLI: Make --prefix an alias for --namePrefix

---

CHANGELOG.md
glide.lock
glide.yaml

And semver (3.0) for dosa-idl.

CHANGELOG for V3

---

CHANGELOG.md
version.go

update change log and version for v3.1.0 release

release v3.1.0

---

.build/lint.mk

Don't search for a substring `fixme`, look for it as a word

Fix the FIXME check

---

range_conditions.go
range_conditions_test.go

Breaking out of a nested loop using a label is barely better than a GOTO, and is a code smell.

Cleanup EnsureValidRangeConditions

---

cmd/dosa/main.go
cmd/dosa/query.go
cmd/dosa/schema.go
glide.lock
glide.yaml

* Add Java client cli support
* Related diff: https://github.com/uber/dosa/pull/47/

Add Java client cli support

---

CHANGELOG.md
version.go

This reverts commit 92df4fe986f5c31b3f166134438228ba1195f27d.

Revert "Release v3.3.1 (#365)"

---

connectors/yarpc/helpers.go
glide.lock

changes because of updated dosa-idl and rpc entityDefinition

Update dosa-idl related

---

glide.lock
glide.yaml

before:
```
vendor/golang.org/x/net/internal/socket/sys_const_unix.go:9:8: cannot find package "golang.org/x/sys/unix"
```
after:
```
make test
PASS
```

Add required package in glide.yaml

---

cmd/dosa/scope.go
cmd/dosa/scope_test.go

Error message violates "solid error reporting" rule 3 from
https://medium.com/@rkuris/good-apis-cd861b8b70a3
Added a test to prevent future breakage

Correct error message

---

cmd/dosa/scope.go

no test needed.
CHANGELOG is not needed.

use uown but not ublame since it's deprecated in Uber

---

CHANGELOG.md
connectors/yarpc/yarpc.go
connectors/yarpc/yarpc_test.go

rename the yarpc and dosarpc in `yarpc.go` and `yarpc_test.go`.
These two files should share the same naming.
run unit test

dosarpc and gorpc naming

---

names.go

From http://cassandra.apache.org/doc/latest/cql/appendices.html

Update the Cassandra reserved-word list

---

connector.go

Update some comments in the Connector API.

---

client.go
names.go
schema/cql/cql_test.go

Update to latest list, and test fixes.

Docstore resvd

---

CHANGELOG.md
connectors/memory/memory.go
connectors/memory/memory_test.go

Thanks to ehsan@uber.com for the report and fix.

Fix memory connector index bug

---

CHANGELOG.md
entity_parser.go
entity_parser_key_parser_test.go

This is an unacceptably bad error message:
`column "Count": invalid name tag:`
Really? A blank tag is an error???

Improve some error messages

---

CHANGELOG.md
connectors/yarpc/yarpc.go
version.go

Do not discard errors from the gateway

---

CHANGELOG.md
names.go
names_test.go
version.go

Until we move to Docstore maybe?

Temporarily remove Docstore reserved words

---

CHANGELOG.md
connectors/cache/fallback.go
connectors/cache/fallback_test.go

Make fallback Cache Scan api call next in line connector's Scan api

Make Fallback Scan call call main scan function

---

CHANGELOG.md

Tested field tags with local build of client talking to local build of gateway.

Release v3.4.30
